export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const VIEWINCIDENT_START = "VIEWINCIDENT_START";
export const VIEWINCIDENT_SUCCESS = "VIEWINCIDENT_SUCCESS";
export const VIEWINCIDENT_FAILURE = "VIEWINCIDENT_FAILURE";

